### ISSUE TITLE
libglasswall.classic.so: no such file or directory

### ISSUE THREAD

**Issue by baker371** [filetrust/c-icap#30]
The path to libglasswall.classic.so is not specified in the docker file, do docker image installation cannot be completed.

![kbd2](https://user-images.githubusercontent.com/8102313/90972969-66891800-e526-11ea-8e8d-85299dd0db49.PNG)

**Comment by dtollaku** [comment]
@baker371 This file is provided by the repo's sub-module, which is a private repo.
You can find here .so: https://github.com/filetrust/Glasswall-Rebuild-SDK-Evaluation/tree/master/Linux/Library
When you have it you can read the instructions at icap-readme https://github.com/filetrust/c-icap

**Comment by BigPeeg** [comment]
The repo has been updated to reference the Evaluation version of the SDK, which is a public repo. Following the README instructions should make the sub-module available.
