### ISSUE TITLE
Logging should be directed to StdOut

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/c-icap#40]
To enable log capture from the container, logs should be written to StdOut rather than to disk. This can be managed by updating the c-icap server configuration to write to 
```
/proc/self/fd/1
```

The following fields should be updated in the c-icap/c-icap/c-icap.conf.in file
```
ServerLog /proc/self/fd/1

AccessLog /proc/self/fd/1
```

**Testing**

- After a rebuild of the code the generated `c-icap/c-icap/c-icap.conf` file should container the following settings
```
ServerLog /proc/self/fd/1

AccessLog /proc/self/fd/1
```
- After an install the file at `/usr/local/c-icap/etc/c-icap.conf should include the updated ServerLog and AccessLog configuration items
- The default log file locations should remain empty when the ICAP server is started
```
/usr/local/c-icap/var/log/server.log

/usr/local/c-icap/var/log/access.log
```

_When installing after any change in default configuration, the local install location (`/usr/local/c-icap`) should be removed to ensure that the files are installed correctly._

**Comment by mpigram** [comment]
I have completed this, added my branch to repo and created a pull request.

All tested within Docker and all is working fine.
